# ReCode by @Kayyzyu
# FROM Kayzyu-Ubot <https://github.com/Kayzyu/Kayzu-Ubot>
# KONTOLLLLLLL

from platform import uname
from userbot import ALIVE_NAME, CMD_HELP
from userbot.events import register

# ================= CONSTANT =================
DEFAULTUSER = str(ALIVE_NAME) if ALIVE_NAME else uname().node
# ============================================


@register(outgoing=True, pattern=r"^\.roas4(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**EH KONTOL SADAR DIRI BEGO BADAN LU KURUS KAYA SAPU LIDI ANJING UDAH KAYA GA DI KASIH MAKAN SAMA ORANG TUANYA BANGSAT OH YA LUPA GUA LU KAN GAPUNYA ORANG TUA ANJING MAKAN AJA MASIH NGAMBIL DI TONG SAMPAH BEGO KASIAN BET NASIB LU TOLOL APA PERLU GUA BANSOS IN BUAT LU MAKAN SEHARI HARI TOLOL NI YA GUA KASIH TAU SAMA LU BEGO SETIDAKNYA KALAU UDAH GABISA CARI MAKAN MENDING MATI AJA BEGO BIAR GA NYUSAHIN ORANG ORANG TOLOL KASIAN BEGO ORANG ORANG NGELIAT LU GA TEGA GTU JADINYA TOLOL**")


@register(outgoing=True, pattern=r"^\.roas5(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**OH IYA GUA LUPA EMAK LU AJA UDAH KAGA ADA KARNA TAU MASA DEPAN ANAK KAYA LU TUH GA BAKAL BENER ANAK SAMA EMAK GA ADA YG BENER KEMARIN AJA EMAK LU LAGI DIENTOT SAMA KENEK TREK YEKAN MEMEKNYA DILONGGARIN PAKE DONGKRAK BIAR PALA KENEK TREKNYA BISA MASUK KE MEMEK MAK LU,MUKA LU AJA KEBANYAKAN KENA AIR KERAS KONTOLUDEH GUA BILANG KALO KOSA KATA MASIH DIKIT TERUS LU PUTER PUTER DOANG GA USAH BELAGU KONTOL KASIAN BEGO ITU MAK LU DISANDRA AMA KOMPENI KARNA KEBANYAKAN HUTANG TERUS DIENTOT SAMA KOMPENI AMPE MEMEK MAK LU BENANAH KORENGAN TERUS KELUAR DARAH YEKAN**")


@register(outgoing=True, pattern=r"^\.roas6(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**MAKANYA KALO PUNYA MATA DI PAKE DILIAT SIAPA YG LU LAWAN TOLOL LU LAWAN ORANG UNLIMITED KOSA KATA JANGAN DILAWAN GOBLOK GK KAYA LU KOSA KATA CUMA GITU GITU DOANG UDEH KETAUAN ITU KEHIDUPAN LU YEKAN UDEH LAH GA USAH UMBAR² DIMARI GUA TAU MALEM MALEM GINI KELAPERAN KAN LU NUNGGUIN TIKUS MATI DIPINGGIR JALAN BUAT LU GADOIN TERUS KALO MINUM PAKE AIR GOT YEKAN MAKANYA KALO HIDUP TUH JANGAN SERBA KEKURANGAN PANTESAN KURANG GIZI MAKANYA KALO PAS KECIL SERINGIN MINUM AIR SUSU IBU BEGO**")


CMD_HELP.update(
    {
        "war4": "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .roas4\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .roas5\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .roas6\
        \n↳ : lihat sendiri\
   "
    }
)
